### ISSUE TITLE
Line 16 & 19 `print`

### ISSUE THREAD

**Issue by JamesDevlin5** [liangxianzhe/nap.nvim#11]
Could we make the print statements notify statements on lines 16 and 19? I'm not sure what the icon/title would be but just a thought; I've been getting errors with githunks not having any more hunks and the lsp no having any diagnostics, if you want to try it out.

**Comment by liangxianzhe** [comment]
Changed to notify. Set title but not icon ( I don't use vim.notify plugin so not sure what is the best icon. ) Let me know if you have a better idea.
