### ISSUE TITLE
Feature request: Make movement compatible with operator and visual mode

### ISSUE THREAD

**Issue by xulongwu4** [liangxianzhe/nap.nvim#12]
Hi, I love your plugin. I am wondering if you can make the movements within a single buffer usable with an operator and in visual mode. For example, if I type `d]d` in normal mode, I would expect the text from the current cursor up to the next diagnostics to be deleted. Thanks in advance.

**Comment by liangxianzhe** [comment]
Hi, added basic support for this. Let me know if you see any issue.

**Comment by xulongwu4** [comment]
It works perfectly. Thanks!
