### ISSUE TITLE
Simplify keymapping

### ISSUE THREAD

**Issue by koopa1338** [liangxianzhe/nap.nvim#13]
Would it be possible to simplify setup of custom keymaps and override existing ones? If I understand the readme correctly you would have to do this for every new operator/overriding existing operator:
```lua
require("nap").nap('h',
    "next function or command",
    "prev function or command",
    "Next description", "Previous description",
)
```

it would be much nicer if we could do this in the setup function with some kind of table, for example:

```lua
require("nap").setup {
  next_prefix = "<c-n>",
  prev_prefix = "<c-p>",
  next_repeat = "<c-n>",
  prev_repeat = "<c-p>",
  operator_maps = {
    ["h"] = {
      next = {
        callback = "function or command",
        description = "description",
      },
      prev = {
        callback = "function or command",
        description = "description",
      },
    },
  },
}
```

EDIT: the defaults can also be included as a default config in the README, which makes therefore obvious what each binding does and also simplifies overriding the existing operators.

**Comment by liangxianzhe** [comment]
Hi @koopa1338, see the commit. Let me know if you have any other suggestions. Thanks!!
