### ISSUE TITLE
Spelling maps don't work

### ISSUE THREAD

**Issue by oncomouse** [liangxianzhe/nap.nvim#4]
The default mappings for `s` (`normal ]s` and `normal [s`) don't work. Without an exclamation at the end, `normal` will use maps when sending keys, which means that `[s` and `]s` will be defined in terms of themselves. [This line](https://github.com/liangxianzhe/nap.nvim/blob/a2892d5882672b45166300f97a8cb77927629e73/lua/nap.lua#L79) should read:

~~~
M.nap("s", "normal! ]s", "normal! [s", "Next spelling error", "Previous spelling error")
~~~

**Comment by liangxianzhe** [comment]
You are right. Fixed. Thanks!!
